### ISSUE TITLE
[Request]  Add emoji customization for `s!f`

### ISSUE THREAD

**Issue by epai** [ktraw2/SplatBot#2]
It would be awesome if we could do something like this:

s!f 🍑

🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑
🍑🍑🍑🍑

Note that it'd probably have to be narrower, because emojis take more room than "F"s.  Syntax would be something like:

`s!f <emote>`

...where <emote> could be an emoji or emoji react (e.g. :gary:)

**Comment by ktraw2** [comment]
Ok, now that is epic

10/10 feature

**Comment by AdamW19** [comment]
Implemented! 

`s!F <any emote>` is now enabled. Note that I had to truncate the "F" due to Discord's 2000 character limit.
