### ISSUE TITLE
[BUG]  Too much minecraft

### ISSUE THREAD

**Issue by epai** [ktraw2/SplatBot#4]
Minecraft is causing the splatoon server bot to not function correctly.

**Comment by AdamW19** [comment]
Hi,

I haven't seen this issue personally, however I do believe @ktraw2 has 1st hand experience with this, so I've assigned him the ticket.

If there's anything else I can help you with, please feel free to ask.

**Comment by ktraw2** [comment]
Fixed as I decided to grief the base I was living in with my friend now I have no base so no reason to play minecraft. Oops...
